include:
  - proxy.yaml

services:
  db:
    image: mysql:9.4.0
    container_name: mysql

    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G
        reservations:
          cpus: '0.12'
          memory: 100M

    env_file:
      - .env
    
    ports:
      - "3306:3306"  # чтобы можно было достучаться снаружи

    networks:
      backend:
        ipv4_address: 172.20.0.10

    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: 
      context: .
      dockerfile: Dockerfile.python

    container_name: python-app

    depends_on:
      - db

    environment:
      - DB_HOST=db
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}

    networks:
      backend:
        ipv4_address: 172.20.0.5

    ports:
      - "5000:5000"

volumes:
  mysql_data:
