FROM python:3.12-slim
RUN apt update 
RUN apt install -y iproute2
RUN mkdir -p /app
WORKDIR /app
COPY requirements.txt /app
RUN pip install -r requirements.txt
COPY main.py /app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"] 
